### ISSUE TITLE
Add support to retrieve the metadata of a key with a Reader role. 

### ISSUE THREAD

**Issue by gicaceres** [IBM/keyprotect-go-client#33]
Currently the `GetKey()` Method needs a Reader Plus role.
Providing a new method `GetKeyMetadata()` to use the `GET /api/v2/keys/{id}/metadata` should solve the problem.

The new method should also return the `deleted`, `dualAuthDelete`, `keyVersion` metadata.
```
"deleted": <true|false>,
"dualAuthDelete": {
    "enabled": <true|false>
},
"keyVersion": {
    "id": "<key-id>"
}
```

**Comment by mrodden** [comment]
Should be available with v0.5.0 now
