### ISSUE TITLE
iam.cloud.ibm.com endpoint is hardcoded

### ISSUE THREAD

**Issue by kavya498** [IBM/keyprotect-go-client#69]
Endpoint should not be hardcoded [here](https://github.com/IBM/keyprotect-go-client/blob/master/iam/iam.go#L32) 

Request to provide ability to override iam endpoint

**Comment by mrodden** [comment]
You are referring to the default URL in your link.

The correct way to provide your own URL for IAM is to provide it when building your own `IAMTokenSource`. The URL can be set during the construction of said struct as `TokenURL`

https://github.com/IBM/keyprotect-go-client/blob/master/iam/iam.go#L99
